import "./globals.css";
import Nav from "./components/Nav";
import Main from "./components/Main";
import Footer from "./components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sans bg-primary flex flex-col gap-16">
        <Nav />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
