import "./globals.css";
import Nav from "./components/Nav";
import Main from "./components/Main";
import Footer from "./components/Footer";

export const metadata = {
  title: "P.P. FreshPork",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="font-sans bg-third flex flex-col gap-16">
        <Nav />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
